### PR TITLE
Added "Server Side the Angular Way" examples

### PR DESCRIPTION
**Pull request by marcosdimitrio**
This is the way I could successfully enable the server side option. It's based on the idea found on a [comment](https://github.com/l-lin/angular-datatables/issues/982#issuecomment-311820425) by [nbiles](https://github.com/nbiles) in which he suggests that we override the [ajax option with a function](https://datatables.net/reference/option/ajax#function).

It has worked great for me and, since this was not easy to find, I thought I could share it as well as help improve the project.

I added two PHP scripts from DataTables [server side example](https://datatables.net/examples/data_sources/server_side.html), slightly modified to work with Angular, as well as a MySQL dump, so you can incorporate it to the website, and to serve as a starting point for the users.

Feel free to use/improve it, and if you ever find a more streamlined way to do it, just go ahead and replace it.

### CODE REVIEW

**Comment by l-lin** [comment]
Awesome! :+1: 

I moved the php server files to [another projet](https://github.com/l-lin/angular-datatables-demo-server) and I deployed it to [heroku](https://angular-datatables-demo-server.herokuapp.com/) so the demo (which use statics files) can call it :)

**Comment by marcosdimitrio** [comment]
Nice! The example is not working though, it's throwing a "Cross-Origin Request Blocked" error, I think there's some config missing.

**Comment by l-lin** [comment]
I don't have the issue in the [example](https://l-lin.github.io/angular-datatables/#/basic/server-side-angular-way). I added the [headers](https://github.com/l-lin/angular-datatables-demo-server/blob/master/web/index.php#L18-L19) so CORS is not enabled :/
Weird.

**Comment by marcosdimitrio** [comment]
That's strange. To me, it gives: 

>Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://angular-datatables-demo-server.herokuapp.com/. (Reason: missing token ‘content-type’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel).

**Comment by marcosdimitrio** [comment]
That's strange. To me, it shows: 

>Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://angular-datatables-demo-server.herokuapp.com/. (Reason: missing token ‘content-type’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel).

**Comment by marcosdimitrio** [comment]
That's strange. To me, this is the message in the console:

>Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://angular-datatables-demo-server.herokuapp.com/. (Reason: missing token ‘content-type’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel).

**Pull request merged**
