### PR TITLE
Fix getList and getLast

### PR DESCRIPTION
**Pull request by miguelqvd**
This fixes the issue when trying to access getList and getLast and the tables haven't been still registered.

This can be tested here: http://plnkr.co/edit/I1BEU6lIdFkAqxxwGadf

### CODE REVIEW

**Comment by miguelqvd** [comment]
I've corrected minor merge issues.

**Comment by l-lin** [comment]
Unfortunately, if you remove the variable assignment in the `$scope`, the console displays `undefined`. See [plnkr](http://plnkr.co/edit/U7xR4acOAZb0MPRp9unS?p=preview). :cry:

**Comment by miguelqvd** [comment]
Sorry, I don't understand your point, the promise returns the instances as expected and the reason because the $scope.instancesFound is undefined is because it has never been assigned.

```javascript
var app = angular.module('plunker', ['datatables']);

app.controller('MainCtrl', function($scope, DTInstances) {
  $scope.name = 'World';
  
  DTInstances.getList().then(function(dtInstances){
    console.log($scope.instancesFound);
  });
  
  $scope.onCheckDTInstancesClick = function(){
      DTInstances.getList().then(function(dtInstances){
        console.log($scope.instancesFetched);
      });
  };
});
```

I think it should be:

```javascript
var app = angular.module('plunker', ['datatables']);

app.controller('MainCtrl', function($scope, DTInstances) {
  $scope.name = 'World';
  
  DTInstances.getList().then(function(dtInstances){
    console.log(dtInstances);
    $scope.instancesFound = dtInstances;
  });
  
  $scope.onCheckDTInstancesClick = function(){
      DTInstances.getList().then(function(dtInstances){
        console.log(dtInstances);
        $scope.instancesFetched = dtInstances;
      });
  };
});
```
I've updated my plunkr http://plnkr.co/edit/I1BEU6lIdFkAqxxwGadf

**Comment by l-lin** [comment]
My bad :sweat_smile: I read your plnkr too quickly and I thought I read `console.log(dtInstances);` instead of `console.log($scope.instancesFound)`. So I thought it could only work if the `dtInstances` is assigned to an Angular `$scope` or linked to the Angular digest (which is not true).

However, your code in the pull request does not work, but the code in your plnkr does.
So I used the latter.

Thanks for your contribution. You're awesome! :+1:

**Pull request closed without merging**
