### PR TITLE
Must convert to HTMLInput

### PR DESCRIPTION
**Pull request by XDavidT**
jQuery return HTMLElement, and need to convert it before using 'value'.

### CODE REVIEW

**Comment by shanmukhateja** [comment]
I'm conflicted with this PR. I understand why it was created but I know for a fact our demo project still works as expected. 

I've thought about this for 2 days and still I don't know if merging this bring something new to the table.

**Comment by shanmukhateja** [comment]
@l-lin I've elected to assign this to you. The decision is yours :)

**Comment by XDavidT** [comment]
> I'm conflicted with this PR. I understand why it was created but I know for a fact our demo project works as expected without this change.
> 
> I've thought about this for 2 days and still I don't know if merging this bring something new to the table.

As you say, it work great in the demo, but me and the next users will be use newer Angular versions, as Angular get updated it need more variable declare and more precision.
I'm sure this is not the first case..

**Comment by l-lin** [comment]
Thanks for the contribution! :clap: 

Can you please update the associated markdown file: https://github.com/l-lin/angular-datatables/blob/master/demo/src/assets/docs/advanced/indi-col-filter/source-ts.md

**Pull request closed without merging**
